export const BREAK_POINT = {
  BREAK_POINT_MOBILE: 360,
  BREAK_POINT_MOBILE_MIN: 360,
  BREAK_POINT_MOBILE_MAX: 767,
  BREAK_POINT_TABLET: 768,
  BREAK_POINT_TABLET_MIN: 768,
  BREAK_POINT_TABLET_MAX: 1199,
  BREAK_POINT_DESKTOP: 1200,
};

export const MEDIA_QUERY = {
  tablet: `max-width : ${BREAK_POINT.BREAK_POINT_TABLET_MAX}px`,
  mobile: `max-width : ${BREAK_POINT.BREAK_POINT_MOBILE_MAX}px`,
};
